joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 250
 
joint7_position_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_7

linear_position_controller:
  type: "position_controllers/JointPositionController"
  joint: openclose